"""Configure or inspect a machine without installing the pipeline or calling AWS."""

from __future__ import annotations

import argparse
import json
import os
import re
import shlex
import shutil
import subprocess
import sys
from pathlib import Path

from .environment import (
    ENV_NAMES,
    INSTALL_DEFAULTS,
    PATH_FIELDS,
    PipelineEnvironment,
    environment_values,
)

PACKAGE_PROBE = """
import importlib.util
import importlib.metadata as metadata
import json
import sys

pins, modules = json.loads(sys.argv[1]), json.loads(sys.argv[2])
python_version = sys.version.split()[0]
python_ok = (not sys.argv[3] or python_version == sys.argv[3]
             or python_version.startswith(sys.argv[3] + '.'))
missing_modules = [name for name in modules if importlib.util.find_spec(name) is None]
versions, missing_distributions = {}, []
for name in pins:
    try:
        versions[name] = metadata.version(name)
    except metadata.PackageNotFoundError:
        versions[name] = None
        missing_distributions.append(name)
mismatched = [name for name, expected in pins.items()
              if expected and versions[name] is not None
              and not (versions[name].split('+')[0] == expected
                       or (name == 'rerun-sdk' and versions[name].startswith(expected + '.')))]
missing = sorted(set(missing_modules + missing_distributions))
print(json.dumps({'python': python_version, 'versions': versions, 'missing': missing,
                  'mismatched': mismatched, 'python_matches': python_ok}))
sys.exit(bool(missing or mismatched or not python_ok))
"""

CUDA_PROBE = """
import sys
try:
    import torch
    available = torch.cuda.is_available()
    print('torch=' + torch.__version__ + ' CUDA build=' + str(torch.version.cuda)
          + ' available=' + str(available))
    if available:
        print(torch.cuda.get_device_name(0))
        torch.empty(1, device='cuda')
except Exception as error:
    print('CUDA check unavailable: ' + str(error))
    sys.exit(1)
sys.exit(0 if available else 2)
"""

OPEN3D_PROBE = """
import sys
try:
    import open3d
    cloud = open3d.geometry.PointCloud()
    print('Open3D=' + open3d.__version__ + ' native point-cloud import ready')
except Exception as error:
    print('Open3D import failed: ' + str(error))
    sys.exit(1)
"""


def configure(env_file: Path, repo: Path) -> None:
    saved = {}
    if env_file.is_file():
        for line in env_file.read_text().splitlines():
            parts = shlex.split(line)
            if len(parts) == 2 and parts[0] == "export" and "=" in parts[1]:
                name, value = parts[1].split("=", 1)
                if name in INSTALL_DEFAULTS or name == "CUDA_HOME":
                    saved[name] = value
    # Shell exports win over the last installation file, including the old alias.
    values = {**saved, **environment_values(os.environ)}
    home = str(Path.home())
    for name, default in INSTALL_DEFAULTS.items():
        if not values.get(name):
            values[name] = default.format(
                home=home, repo=repo, data=values.get("RECON_DATA_ROOT")
            )
    # Prefer the existing managed Conda installation; otherwise install in $HOME.
    if (
        not os.environ.get("RECON_CONDA_BOOTSTRAP")
        and not Path(values["RECON_CONDA_BOOTSTRAP"]).is_file()
    ):
        candidates = [
            Path(home) / name / "etc/profile.d/conda.sh"
            for name in ("miniforge3", "miniconda3")
        ]
        values["RECON_CONDA_BOOTSTRAP"] = str(
            next((p for p in candidates if p.is_file()), candidates[0])
        )
    environment = PipelineEnvironment.from_environ(values)
    lines = ["# Generated by scripts/setup_environment.sh; machine settings only."]
    lines.extend(
        f"export {name}={shlex.quote(values[name])}" for name in INSTALL_DEFAULTS
    )
    cuda_home = os.environ.get("CUDA_HOME") or saved.get("CUDA_HOME")
    if not cuda_home:
        nvcc = shutil.which("nvcc")
        cuda_home = (
            str(Path(nvcc).parent.parent)
            if nvcc
            else str(environment.nerfstudio_bin.parent)
        )
    lines.extend(
        [
            f"export CUDA_HOME={shlex.quote(cuda_home)}",
            "# Conda CUDA headers live under targets; gsplat also compiles C++ sources.",
            'if [ -f "$CUDA_HOME/targets/x86_64-linux/include/cuda_runtime_api.h" ]; then',
            '  case ":${CPATH:-}:" in',
            '    *":$CUDA_HOME/targets/x86_64-linux/include:"*) ;;',
            '    *) CPATH="$CUDA_HOME/targets/x86_64-linux/include${CPATH:+:$CPATH}" ;;',
            "  esac",
            "  export CPATH",
            "fi",
            "export PATH="
            + shlex.quote(str(environment.python.parent))
            + ":"
            + shlex.quote(str(environment.nerfstudio_bin))
            + ":"
            + shlex.quote(str(environment.splat_transform_prefix / "bin"))
            + ':"$PATH"',
            f"if [ -x {shlex.quote(str(environment.nerfstudio_bin / 'x86_64-conda-linux-gnu-c++'))} ]; then export CXX={shlex.quote(str(environment.nerfstudio_bin / 'x86_64-conda-linux-gnu-c++'))}; fi",
            'export LD_LIBRARY_PATH="$CUDA_HOME/lib:${LD_LIBRARY_PATH:-}"',
        ]
    )
    env_file.parent.mkdir(parents=True, exist_ok=True)
    temporary = env_file.with_suffix(".tmp")
    temporary.write_text("\n".join(lines) + "\n")
    temporary.chmod(0o600)
    temporary.replace(env_file)
    source_line = (
        f"[ -f {shlex.quote(str(env_file))} ] && . {shlex.quote(str(env_file))}"
    )
    login_startup = next(
        (
            Path.home() / name
            for name in (".bash_profile", ".bash_login", ".profile")
            if (Path.home() / name).exists()
        ),
        Path.home() / ".bash_profile",
    )
    for startup in (Path.home() / ".bashrc", login_startup):
        existing = startup.read_text() if startup.exists() else ""
        if source_line not in existing.splitlines():
            with startup.open("a") as handle:
                handle.write(
                    "\n# Reconstruction pipeline environment\n" + source_line + "\n"
                )
    print(f"Saved environment: {env_file}")
    print(f"Load it in this terminal: source {shlex.quote(str(env_file))}")


def check_environment(*, require_cuda: bool = False) -> dict:
    """Collect all findings instead of failing on the first unset variable."""
    checks = []

    def record(name, okay, detail, *, warning=False):
        checks.append(
            {
                "check": name,
                "status": "OK" if okay else ("WARN" if warning else "FAIL"),
                "detail": str(detail),
            }
        )

    def executable(path):
        return path.is_file() and os.access(path, os.X_OK)

    def probe(name, command, *, warning=False):
        try:
            completed = subprocess.run(
                command, capture_output=True, text=True, timeout=20
            )
            detail = "\n".join(
                part
                for part in (completed.stdout.strip(), completed.stderr.strip())
                if part
            )[-2000:]
            record(
                name,
                completed.returncode == 0,
                detail or f"exit {completed.returncode}",
                warning=warning and completed.returncode == 2,
            )
        except (OSError, subprocess.TimeoutExpired) as error:
            record(name, False, error)

    values = environment_values(os.environ)
    for field, name in ENV_NAMES.items():
        value = values.get(name, "")
        okay = bool(value.strip())
        if okay and field in PATH_FIELDS:
            okay = Path(value).expanduser().is_absolute()
        record(name, okay, value if value else "not exported")

    # Check available paths even when other variables are absent.
    def path(name):
        value = values.get(name)
        return (
            Path(value).expanduser()
            if value and Path(value).expanduser().is_absolute()
            else None
        )

    bootstrap = path("RECON_CONDA_BOOTSTRAP")
    if bootstrap:
        record("Conda bootstrap", bootstrap.is_file(), bootstrap)
    root = path("RECON_PIPELINE_ROOT")
    if root:
        for relative in (
            ".git",
            "pyproject.toml",
            "src/recon_pipeline/environment.py",
            "scripts/setup_environment.sh",
        ):
            record("pipeline: " + relative, (root / relative).exists(), root / relative)
    upstream = path("RECON_FOURDANYONE_ROOT")
    if upstream:
        for relative in (
            ".git",
            "requirements.txt",
            "inference.py",
            "scripts/export_nerfstudio.py",
            "third_party/GVHMR/hmr4d/__init__.py",
        ):
            record(
                "4DAnyone: " + relative,
                (upstream / relative).exists(),
                upstream / relative,
            )
        if shutil.which("git") and (upstream / ".git").exists():
            try:
                head = subprocess.check_output(
                    ["git", "-C", str(upstream), "rev-parse", "HEAD"],
                    text=True,
                    timeout=5,
                ).strip()
                expected = values.get("RECON_FOURDANYONE_GIT_REF")
                if expected:
                    expected = subprocess.check_output(
                        [
                            "git",
                            "-C",
                            str(upstream),
                            "rev-parse",
                            expected + "^{commit}",
                        ],
                        text=True,
                        stderr=subprocess.PIPE,
                        timeout=5,
                    ).strip()
                record(
                    "4DAnyone revision",
                    head == expected,
                    head,
                )
            except (OSError, subprocess.SubprocessError) as error:
                record("4DAnyone revision", False, error)
    data = path("RECON_DATA_ROOT")
    if data:
        for relative in ("", "input", "models", "runs", "jobs", "environment"):
            folder = data / relative
            record(
                "workspace: " + (relative or "root"),
                folder.is_dir() and os.access(folder, os.W_OK),
                folder,
            )
    lock = path("RECON_LOCK_FILE")
    if lock:
        record("4DAnyone package lock", lock.is_file(), lock)

    conda = path("RECON_CONDA_ENV")
    ns_bin = path("RECON_NERFSTUDIO_BIN")
    rerun_python = path("RECON_SPLATFACTO_RERUN_PYTHON")
    interpreters = [
        (
            "4DAnyone",
            conda / "bin/python" if conda else None,
            {
                "torch": values.get("RECON_TORCH_VERSION"),
                "torchvision": values.get("RECON_TORCHVISION_VERSION"),
            },
            [
                "recon_pipeline",
                "boto3",
                "telebot",
                "rerun",
                "av",
                "cv2",
                "einops",
                "kornia",
                "smplx",
                "timm",
                "transformers",
                "ultralytics",
            ],
        ),
        (
            "Splatfacto",
            ns_bin / "python" if ns_bin else None,
            {
                "torch": values.get("RECON_SPLATFACTO_TORCH_VERSION"),
                "torchvision": values.get("RECON_SPLATFACTO_TORCHVISION_VERSION"),
                "nerfstudio": values.get("RECON_NERFSTUDIO_VERSION"),
                "gsplat": values.get("RECON_GSPLAT_VERSION"),
            },
            ["recon_pipeline", "cv2", "numpy", "PIL", "ninja", "nerfstudio", "gsplat"],
        ),
        (
            "Splatfacto Rerun",
            rerun_python,
            {"rerun-sdk": "0.36"},
            ["recon_pipeline", "rerun", "numpy", "PIL", "plyfile", "tensorboard"],
        ),
    ]
    for name, python, pins, modules in interpreters:
        if not python:
            continue
        record(name + " Python", executable(python), python)
        if not executable(python):
            continue
        probe(
            name + " packages",
            [
                str(python),
                "-c",
                PACKAGE_PROBE,
                json.dumps(pins),
                json.dumps(modules),
                values.get("RECON_PYTHON_VERSION", ""),
            ],
        )
        if name == "Splatfacto":
            # find_spec alone cannot detect missing native libraries such as EGL.
            probe(name + " Open3D", [str(python), "-c", OPEN3D_PROBE])
        if name != "Splatfacto Rerun":
            # Torch import/allocation checks driver access, but never compiles gsplat.
            probe(
                name + " CUDA",
                [
                    str(python),
                    "-c",
                    CUDA_PROBE,
                ],
                warning=not require_cuda,
            )
    if conda:
        for name in ("ffmpeg", "recon-config", "recon-aws-worker"):
            record(name, executable(conda / "bin" / name), conda / "bin" / name)
    if ns_bin:
        for name in ("ns-train", "ns-export"):
            record(name, executable(ns_bin / name), ns_bin / name)
    transform_prefix = path("RECON_SPLAT_TRANSFORM_PREFIX")
    if transform_prefix:
        node = transform_prefix / "bin/node"
        converter = transform_prefix / "bin/splat-transform"
        record("splat-transform Node.js", executable(node), node)
        record("splat-transform executable", executable(converter), converter)
        if executable(node):
            probe(
                "splat-transform Node.js version",
                [
                    str(node),
                    "-e",
                    "console.log(process.version); process.exit(Number(process.versions.node.split('.')[0]) >= 22 ? 0 : 1)",
                ],
            )
        if executable(node) and executable(converter):
            try:
                completed = subprocess.run(
                    [str(node), str(converter), "--version"],
                    capture_output=True,
                    text=True,
                    timeout=20,
                )
                match = re.search(r"splat-transform v(\S+)", completed.stdout)
                expected = values.get("RECON_SPLAT_TRANSFORM_VERSION")
                record(
                    "splat-transform version",
                    completed.returncode == 0 and bool(match) and match[1] == expected,
                    (
                        f"{completed.stdout.strip()} (expected {expected})"
                        if completed.returncode == 0
                        else completed.stderr.strip()
                    ),
                )
            except (OSError, subprocess.TimeoutExpired) as error:
                record("splat-transform version", False, error)
    cuda_home = path("CUDA_HOME")
    nvcc = (
        cuda_home / "bin/nvcc"
        if cuda_home
        else (Path(shutil.which("nvcc")) if shutil.which("nvcc") else None)
    )
    record(
        "CUDA compiler",
        bool(nvcc and executable(nvcc)),
        nvcc or "set CUDA_HOME to the toolkit root",
    )
    cxx = os.environ.get("CXX") or shutil.which("c++")
    if nvcc and executable(nvcc):
        try:
            completed = subprocess.run(
                [str(nvcc), "--version"], capture_output=True, text=True, timeout=5
            )
            match = re.search(r"release (\d+\.\d+)", completed.stdout)
            expected = values.get("RECON_CUDA_VERSION", "")
            if completed.returncode or not match:
                record(
                    "CUDA toolkit version",
                    False,
                    (completed.stdout + completed.stderr).strip()
                    or "could not read nvcc version",
                )
            elif not expected:
                record(
                    "CUDA toolkit version",
                    False,
                    f"detected {match[1]}; comparison skipped: RECON_CUDA_VERSION not exported",
                    warning=True,
                )
            else:
                record(
                    "CUDA toolkit version",
                    match[1] == ".".join(expected.split(".")[:2]),
                    f"detected {match[1]}, expected {expected}",
                )
        except (OSError, subprocess.TimeoutExpired) as error:
            record("CUDA toolkit version", False, error)
    record(
        "C++ compiler",
        bool(cxx and (shutil.which(cxx) or executable(Path(cxx)))),
        cxx or "install a C++ compiler",
    )
    if upstream and data and conda and executable(conda / "bin/python"):
        probe(
            "4DAnyone model assets",
            [
                str(conda / "bin/python"),
                "-c",
                "import sys; from pathlib import Path; sys.path.insert(0,sys.argv[1]); "
                "from fdanyone.assets import MODEL_FILES,BIREFNET_DIR,BIREFNET_FILES,SMPLX_MODEL; "
                "root=Path(sys.argv[2]); required=[*(root/p for p in MODEL_FILES),*(root/BIREFNET_DIR/p for p in BIREFNET_FILES),root/SMPLX_MODEL]; "
                "missing=[str(p) for p in required if not p.is_file()]; print('Missing: '+str(missing) if missing else str(len(required))+' assets present'); sys.exit(bool(missing))",
                str(upstream),
                str(data / "models"),
            ],
        )
    return {"ok": not any(c["status"] == "FAIL" for c in checks), "checks": checks}


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest="command", required=True)
    setup = commands.add_parser("configure")
    setup.add_argument("--env-file", type=Path, required=True)
    setup.add_argument("--repo", type=Path, required=True)
    value = commands.add_parser("value")
    value.add_argument("field", choices=list(ENV_NAMES))
    check = commands.add_parser("check")
    check.add_argument("--json", action="store_true")
    check.add_argument("--require-cuda", action="store_true")
    args = parser.parse_args(argv)
    if args.command == "configure":
        configure(args.env_file.expanduser().resolve(), args.repo.resolve())
    elif args.command == "value":
        print(getattr(PipelineEnvironment.from_environ(), args.field))
    else:
        report = check_environment(require_cuda=args.require_cuda)
        if args.json:
            print(json.dumps(report, indent=2))
        else:
            for check in report["checks"]:
                print(f"[{check['status']}] {check['check']}: {check['detail']}")
            print(
                "Environment ready" if report["ok"] else "Environment needs attention"
            )
        return 0 if report["ok"] else 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
