#!/usr/bin/env python3
"""Generate documentation from CLI parsers and environment/profile definitions.

Only the standard library and this checkout are required. Parser construction is
intercepted before argument parsing, so no operation, installation or AWS call runs.
"""

import argparse
import html
import importlib
import json
from pathlib import Path
import sys
import tomllib
from unittest.mock import patch

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))


class ParserCaptured(BaseException):
    def __init__(self, parser):
        self.parser = parser


def capture_parser(parser, *args, **kwargs):
    raise ParserCaptured(parser)


def cell(value):
    return html.escape(str(value), quote=False).replace("|", "\\|").replace("\n", " ")


def default_value(value):
    if value is None:
        return "—"
    if isinstance(value, Path):
        return str(value)
    return json.dumps(value, ensure_ascii=False)


def arguments(parser):
    lines = [
        "| Аргумент | Обязательный | Тип / количество | Default | Описание / choices |",
        "| --- | --- | --- | --- | --- |",
    ]
    children = []
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            children.extend(action.choices.items())
            continue
        if action.help == argparse.SUPPRESS or isinstance(action, argparse._HelpAction):
            continue
        flags = ", ".join(action.option_strings) or action.dest
        kind = getattr(action.type, "__name__", "str")
        if action.nargs == 0:
            kind = "flag"
        elif action.nargs is not None:
            kind += f" / {action.nargs}"
        description = action.help or "—"
        if action.choices is not None:
            description += "; choices: " + ", ".join(map(str, action.choices))
        if isinstance(action, argparse._AppendAction):
            description += "; можно повторять"
        lines.append(
            "| " + " | ".join([
                f"`{cell(flags)}`",
                "да" if action.required else "нет",
                cell(kind),
                f"`{cell(default_value(action.default))}`",
                cell(description),
            ]) + " |"
        )
    return "\n".join(lines), children


def cli_reference():
    scripts = tomllib.loads((ROOT / "pyproject.toml").read_text())["project"]["scripts"]
    parts = [
        "# Все аргументы CLI\n",
        "<!-- Generated by scripts/generate_docs_reference.py. Do not edit by hand. -->\n",
        "Таблицы получены из реальных argparse parsers. Default `—` означает None; "
        "runtime validation может требовать дополнительные сочетания полей. "
        "Для bool flags перечислены positive/negative формы, если они поддержаны.\n",
        "[Назначение утилит, примеры запуска и формат результатов](./utilities.md). "
        "`recon-config` и `recon-aws-worker` — команды orchestration; остальные — операции.\n",
    ]
    for command, target in scripts.items():
        module_name, function = target.split(":")
        module = importlib.import_module(module_name)
        with patch.object(argparse.ArgumentParser, "parse_args", capture_parser):
            try:
                getattr(module, function)(["--help"])
            except ParserCaptured as captured:
                parser = captured.parser
            else:
                raise RuntimeError(f"No parser captured for {command}")
        table, children = arguments(parser)
        parts.extend([
            f"## {command}\n",
            f"Модуль: `{module_name}`. "
            f"[Исходник](https://github.com/vinneyto/4da_3dgs_pipeline/blob/main/src/{module_name.replace('.', '/')}.py).\n",
        ])
        if children:
            parts.append("Подкоманды: " + ", ".join(f"`{name}`" for name, _ in children) + ".\n")
            for name, child in children:
                child_table, _ = arguments(child)
                parts.extend([f"### {command} {name}\n", child_table + "\n"])
        else:
            parts.append(table + "\n")
    return "\n".join(parts)


def environment_reference():
    from recon_pipeline.environment import ENV_NAMES, INSTALL_DEFAULTS, PATH_FIELDS

    lines = [
        "# Переменные окружения\n",
        "<!-- Generated by scripts/generate_docs_reference.py. Do not edit by hand. -->\n",
        "Все перечисленные переменные обязательны при `PipelineEnvironment.from_environ()`, "
        "даже если отдельная стадия выключена. Defaults применяются только installer. "
        "`{home}` — домашний каталог, `{repo}` — checkout, `{data}` — выбранный data root.\n",
        "[Установка, приоритет значений и проверки](../guide/environment.md). "
        "Alias `RECON_NS_BIN` применяется только при отсутствии `RECON_NERFSTUDIO_BIN`.\n",
        "| Переменная | Runtime поле | Тип | Installer default |",
        "| --- | --- | --- | --- |",
    ]
    for field, name in ENV_NAMES.items():
        kind = "абсолютный путь" if field in PATH_FIELDS else "строка"
        lines.append(f"| `{name}` | `{field}` | {kind} | `{INSTALL_DEFAULTS[name]}` |")
    lines.extend([
        "\nВерсии, URL и ref — machine settings, а не experiment parameters. "
        "Сам runtime loader проверяет наличие и абсолютность путей; совместимость "
        "установленных пакетов проверяет `check_environment.sh`.\n",
        "`RECON_ENV_FILE` выбирает env file installer; `CUDA_HOME`, `CXX`, `CPATH`, "
        "`PATH`, `LD_LIBRARY_PATH` используются установленными инструментами. "
        "AWS credentials/profile и Telegram token — отдельные настройки SDK/канала, "
        "не поля `PipelineEnvironment`.\n",
    ])
    return "\n".join(lines)


def training_reference():
    from dataclasses import asdict
    from recon_pipeline.utilities.reconstructions.nerfstudio._profile import TrainingProfile

    lines = [
        "# Defaults профиля Splatfacto\n",
        "<!-- Generated by scripts/generate_docs_reference.py. Do not edit by hand. -->\n",
        "[Смысл полей и ограничения](./config.md#профиль-splatfacto). "
        "Параметры utility имеют kebab-case, а JSON — snake_case. "
        "У `recon-config` флаги профиля дополнительно имеют prefix `--splatfacto-`.\n",
        "| Поле JSON | Тип | Default | Utility flag |",
        "| --- | --- | --- | --- |",
    ]
    for name, value in asdict(TrainingProfile()).items():
        kind = {bool: "boolean", int: "integer", float: "number"}[type(value)]
        flag = "--" + name.replace("_", "-")
        lines.append(f"| `{name}` | {kind} | `{json.dumps(value)}` | `{flag}` |")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    pages = {
        "cli.md": cli_reference(),
        "environment.md": environment_reference(),
        "training-defaults.md": training_reference(),
    }
    stale = []
    for filename, content in pages.items():
        path = ROOT / "docs/reference" / filename
        if args.check:
            if not path.is_file() or path.read_text() != content:
                stale.append(path.relative_to(ROOT).as_posix())
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
            print(f"Generated {path.relative_to(ROOT)}")
    if stale:
        print("Stale reference: " + ", ".join(stale), file=sys.stderr)
        print("Run npm run docs:reference and commit the updated pages.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
